# Browser-Based Private Application Examples
#
# This example demonstrates three browser-accessible private application patterns:
#
#   1. Basic browser app — uses the auto-generated Netskope URL
#   2. Custom hostname   — friendly FQDN (e.g., dashboard.company.com)
#   3. URI auth bypass   — API/webhook endpoints that skip SAML authentication
#
# Use cases: Internal web apps, dashboards, admin panels, and API gateways
# that should be accessible via browser from anywhere.
#
# =============================================================================
# IMPORTANT NOTES:
# =============================================================================
#
# 1. Browser-based vs client-based apps use MUTUALLY EXCLUSIVE fields:
#
#    Browser-based (this example):
#      - real_host             = required (actual backend FQDN, no IPs or wildcards)
#      - private_app_protocol  = required (http or https only)
#      - protocols             = required (single tcp entry matching private_app_protocol port)
#      - clientless_access     = true
#      - private_app_hostname is auto-generated by Netskope (do not set)
#
#    Client-based (see client-app example):
#      - private_app_hostname = user-specified hosts/IPs (supports wildcards, CIDR)
#      - protocols            = required (array of tcp/udp + port pairs, multiple allowed)
#      - clientless_access    = false
#
#    If you need both access methods for the same resource, create two
#    separate app definitions.
#
# 2. real_host MUST be a FQDN (not an IP address)
#    WRONG: real_host = "192.168.10.50"
#    RIGHT: real_host = "wiki.internal.local"
#    The API will reject IPs: "Enter a FQDN. x.x.x.x is not a valid host"
#
# 3. is_user_portal_app = true may not be allowed on all Netskope tenants
#    If you get "User Portal App cannot be created" error, set this to false
#
# 4. Requires SAML Reverse Proxy configuration as a prerequisite
#
# 5. This example requires at least one publisher to exist in your tenant
#    Run publisher-management example first if you don't have publishers
#
# See: https://docs.netskope.com/en/configure-browser-access-for-private-apps/
#
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    netskope = {
      source  = "netskopeoss/netskope"
      version = ">= 0.3.6"
    }
  }
}

provider "netskope" {
  # Configure via environment variables:
  # NETSKOPE_SERVER_URL = "https://your-tenant.goskope.com/api/v2"
  # NETSKOPE_API_KEY    = "your-api-token"
}

# =============================================================================
# VARIABLES
# =============================================================================

variable "publisher_name" {
  description = "Name of the publisher to use (must exist in your tenant)"
  type        = string
  default     = null # Set to null to use the first available publisher
}

# =============================================================================
# DATA SOURCES
# =============================================================================

# Look up existing publishers to assign to the app
data "netskope_npa_publishers_list" "all" {}

# Find the publisher by name, or use the first one if no name specified
locals {
  # Pattern: Conditional publisher selection
  #
  # This demonstrates two common Terraform patterns:
  #
  # 1. Ternary operator (condition ? true_value : false_value)
  #    - If var.publisher_name is set, search for that specific publisher
  #    - If null, fall back to the first available publisher
  #
  # 2. For-expression filtering: [for item in list : item if condition]
  #    - Iterates through all publishers
  #    - Returns only those matching the name
  #    - [0] gets the first (and should be only) match
  #
  # Result: A single publisher object with .publisher_id and .publisher_name
  #
  publisher = var.publisher_name != null ? (
    [for p in data.netskope_npa_publishers_list.all.data.publishers : p if p.publisher_name == var.publisher_name][0]
  ) : data.netskope_npa_publishers_list.all.data.publishers[0]
}

# =============================================================================
# Example 1: Basic Browser App
# =============================================================================
# A simple browser-accessible private app using the Netskope-generated URL.

resource "netskope_npa_private_app" "internal_wiki" {
  private_app_name = "Internal Wiki"

  # Browser-based apps: set private_app_protocol (http or https)
  # Do NOT set private_app_hostname — it is auto-generated by Netskope
  private_app_protocol = "https"

  # real_host is the actual backend FQDN that Netskope proxies to
  # MUST be a FQDN, not an IP address
  real_host = "wiki.internal.local"

  # Enable browser/clientless access — required for browser-based apps
  clientless_access = true

  # NOTE: is_user_portal_app may not be allowed on all tenants
  # If you get "User Portal App cannot be created", set this to false
  is_user_portal_app = true

  # protocols is required for all app types, including browser-based.
  # For browser apps, specify a single TCP entry matching private_app_protocol:
  #   https -> tcp/443, http -> tcp/80
  protocols = [
    {
      port     = "443"
      protocol = "tcp"
    }
  ]

  publishers = [
    {
      publisher_id   = tostring(local.publisher.publisher_id)
      publisher_name = local.publisher.publisher_name
    }
  ]

  # Security settings
  trust_self_signed_certs    = false
  use_publisher_dns          = true
  allow_unauthenticated_cors = false
}

# =============================================================================
# Example 2: Browser App with Custom Hostname
# =============================================================================
# Instead of the Netskope-generated encoded URL (ns-xxxxx-443-tenant.goskope.com),
# use a friendly FQDN like "dashboard.company.com".
#
# IMPORTANT: custom_host is a READ-ONLY computed field in the v2 REST API.
# It cannot be set directly via Terraform or the API. The custom hostname is
# derived from the CN (Common Name) of a certificate uploaded through the
# Netskope UI. The workflow is:
#
#   1. Create the browser app (via Terraform or UI)
#   2. In the Netskope UI, edit the app and enable the "Custom Hostname" toggle
#   3. Upload a certificate and key pair — the cert's CN becomes the custom_host
#      (UI: edit the app > Custom Hostname toggle > Upload Certificate)
#   4. Create a DNS CNAME record pointing the custom hostname to the
#      Netskope-generated Public Host URL (shown in the app_hostname output)
#
# The custom_host value will then appear in Terraform state on the next
# refresh/plan as a computed attribute.
#
# Note: The certificate upload uses a legacy UI endpoint
# (/settings/certificates/createPrivateApps) that is not part of the v2 REST
# API, so it cannot currently be automated via Terraform.
#
# See: https://docs.netskope.com/en/configure-browser-access-for-private-apps/

resource "netskope_npa_private_app" "dashboard_custom_host" {
  private_app_name     = "Engineering Dashboard"
  private_app_protocol = "https"
  real_host            = "dashboard.internal.local"
  clientless_access    = true
  is_user_portal_app   = false

  # custom_host is READ-ONLY — do not set it here.
  # It is populated automatically when a certificate is uploaded via the UI.
  # After uploading, run `terraform refresh` to see the value in state.

  # hide_app_in_portal controls visibility in the Browser Access User Portal.
  # Requires the User Portal feature flag to be enabled on your tenant.
  # Set to true for apps that should not appear in the portal (e.g., API-only
  # backends, or apps accessed exclusively via direct URL).
  hide_app_in_portal = false

  # Enterprise Browser — enables upgrade_insecure_requests and other advanced
  # browser access features. Requires the Enterprise Browser feature flag
  # (npa_mixed_content_enabled) on your tenant. Without it, the API returns an error.
  # enterprise_browser        = true  # Uncomment if Enterprise Browser is enabled
  # upgrade_insecure_requests = true  # Requires enterprise_browser = true

  protocols = [
    {
      port     = "443"
      protocol = "tcp"
    }
  ]

  publishers = [
    {
      publisher_id   = tostring(local.publisher.publisher_id)
      publisher_name = local.publisher.publisher_name
    }
  ]

  trust_self_signed_certs    = false
  use_publisher_dns          = true
  allow_unauthenticated_cors = false
}

# =============================================================================
# Example 3: Browser App with URI Authentication Bypass
# =============================================================================
# Some browser-access apps expose API endpoints or webhook URLs that cannot
# carry SAML authentication cookies. The URI bypass feature allows specific
# paths to skip authentication, provided the request includes the HTTP header:
#
#   X-NSKP-URIBYPASS: <your-configured-secret-value>
#
# Use cases:
#   - REST API endpoints called by external services or CI/CD pipelines
#   - Webhook receivers (e.g., from GitHub, Slack, PagerDuty)
#   - Health check endpoints hit by load balancers or monitoring tools
#
# IMPORTANT: This is a feature-flagged capability. Contact Netskope Support
# to enable the NPA Bypass URI feature on your tenant before using these fields.
#
# See: https://docs.netskope.com/en/browser-access-authentication-bypass-for-uris/

resource "netskope_npa_private_app" "api_with_bypass" {
  private_app_name     = "Internal API Gateway"
  private_app_protocol = "https"
  real_host            = "api.internal.local"
  clientless_access    = true
  is_user_portal_app   = false
  hide_app_in_portal   = true # API-only backend, no need to show in portal

  # allow_uri_bypass enables the URI authentication bypass feature
  allow_uri_bypass = true

  # bypass_uris lists the specific URI paths that skip SAML authentication.
  # - Up to 20 URIs per app definition
  # - Regular expressions are NOT supported
  # - A bare "/" is NOT supported
  # - Each URI must be a path (not a full URL)
  bypass_uris = [
    "/api/v1/webhooks/github",
    "/api/v1/webhooks/slack",
    "/healthz",
  ]

  # uribypass_header_value is the shared secret that must be sent in the
  # X-NSKP-URIBYPASS HTTP header for bypass requests to be accepted.
  # Must be 8-64 characters. Treat this as a secret.
  #
  # Example curl request using the bypass:
  #   curl -H 'X-NSKP-URIBYPASS: mySecretBypassToken123' \
  #     https://ns-xxxxx-443-tenant.goskope.com/api/v1/webhooks/github
  #
  # Without the correct header, even bypass URIs redirect to IdP (302).
  uribypass_header_value = "mySecretBypassToken123"

  protocols = [
    {
      port     = "443"
      protocol = "tcp"
    }
  ]

  publishers = [
    {
      publisher_id   = tostring(local.publisher.publisher_id)
      publisher_name = local.publisher.publisher_name
    }
  ]

  trust_self_signed_certs = false
  use_publisher_dns       = true
}

# =============================================================================
# OUTPUTS
# =============================================================================

output "wiki_app_name" {
  description = "Name of the basic browser app"
  value       = netskope_npa_private_app.internal_wiki.private_app_name
}

output "wiki_app_hostname" {
  description = "Auto-generated hostname for the basic browser app"
  value       = netskope_npa_private_app.internal_wiki.private_app_hostname
}

output "dashboard_custom_host" {
  description = "Custom hostname (read-only, set via cert upload in UI)"
  value       = netskope_npa_private_app.dashboard_custom_host.custom_host
}

output "dashboard_app_hostname" {
  description = "Netskope-generated hostname (use as DNS CNAME target for custom_host)"
  value       = netskope_npa_private_app.dashboard_custom_host.private_app_hostname
}

output "api_app_hostname" {
  description = "Hostname for the API gateway with URI bypass"
  value       = netskope_npa_private_app.api_with_bypass.private_app_hostname
}

output "publisher_used" {
  description = "Publisher assigned to these applications"
  value       = local.publisher.publisher_name
}
