# Browser-Based Private Application Example
#
# This example demonstrates how to create a browser-accessible private application
# that users can access through the Netskope web portal without requiring the NPA client.
#
# Use case: Internal web applications like wikis, dashboards, or admin panels
# that should be accessible via browser from anywhere.
#
# =============================================================================
# IMPORTANT NOTES:
# =============================================================================
#
# 1. Browser-based vs client-based apps use MUTUALLY EXCLUSIVE fields:
#
#    Browser-based (this example):
#      - real_host             = required (actual backend FQDN, no IPs or wildcards)
#      - private_app_protocol  = required (http or https only)
#      - clientless_access     = true
#      - private_app_hostname is auto-generated by Netskope (do not set)
#      - Do NOT set: protocols array (browser apps use private_app_protocol)
#
#    Client-based (see client-app example):
#      - private_app_hostname = user-specified hosts/IPs (supports wildcards, CIDR)
#      - protocols            = required (array of tcp/udp + port pairs)
#      - clientless_access    = false
#
#    If you need both access methods for the same resource, create two
#    separate app definitions.
#
# 2. real_host MUST be a FQDN (not an IP address)
#    WRONG: real_host = "192.168.10.50"
#    RIGHT: real_host = "wiki.internal.local"
#    The API will reject IPs: "Enter a FQDN. x.x.x.x is not a valid host"
#
# 3. is_user_portal_app = true may not be allowed on all Netskope tenants
#    If you get "User Portal App cannot be created" error, set this to false
#
# 4. Requires SAML Reverse Proxy configuration as a prerequisite
#
# 5. This example requires at least one publisher to exist in your tenant
#    Run publisher-management example first if you don't have publishers
#
# See: https://docs.netskope.com/en/configure-browser-access-for-private-apps/
#
# =============================================================================

terraform {
  required_version = ">= 1.0"

  required_providers {
    netskope = {
      source  = "netskopeoss/netskope"
      version = ">= 0.3.4"
    }
  }
}

provider "netskope" {
  # Configure via environment variables:
  # NETSKOPE_SERVER_URL = "https://your-tenant.goskope.com/api/v2"
  # NETSKOPE_API_KEY    = "your-api-token"
}

# =============================================================================
# VARIABLES
# =============================================================================

variable "publisher_name" {
  description = "Name of the publisher to use (must exist in your tenant)"
  type        = string
  default     = null # Set to null to use the first available publisher
}

# =============================================================================
# DATA SOURCES
# =============================================================================

# Look up existing publishers to assign to the app
data "netskope_npa_publishers_list" "all" {}

# Find the publisher by name, or use the first one if no name specified
locals {
  # Pattern: Conditional publisher selection
  #
  # This demonstrates two common Terraform patterns:
  #
  # 1. Ternary operator (condition ? true_value : false_value)
  #    - If var.publisher_name is set, search for that specific publisher
  #    - If null, fall back to the first available publisher
  #
  # 2. For-expression filtering: [for item in list : item if condition]
  #    - Iterates through all publishers
  #    - Returns only those matching the name
  #    - [0] gets the first (and should be only) match
  #
  # Result: A single publisher object with .publisher_id and .publisher_name
  #
  publisher = var.publisher_name != null ? (
    [for p in data.netskope_npa_publishers_list.all.data.publishers : p if p.publisher_name == var.publisher_name][0]
  ) : data.netskope_npa_publishers_list.all.data.publishers[0]
}

# Create a browser-accessible private application
resource "netskope_npa_private_app" "internal_wiki" {
  private_app_name = "Internal Wiki"

  # Browser-based apps: set private_app_protocol (http or https)
  # Do NOT set private_app_hostname — it is auto-generated by Netskope
  private_app_protocol = "https"

  # real_host is the actual backend FQDN that Netskope proxies to
  # MUST be a FQDN, not an IP address
  real_host = "wiki.internal.local"

  # Enable browser/clientless access — required for browser-based apps
  clientless_access = true

  # NOTE: is_user_portal_app may not be allowed on all tenants
  # If you get "User Portal App cannot be created", set this to false
  is_user_portal_app = true

  # Assign to publisher - uses publisher_name variable if set, otherwise first available
  publishers = [
    {
      publisher_id   = tostring(local.publisher.publisher_id)
      publisher_name = local.publisher.publisher_name
    }
  ]

  # Security settings
  trust_self_signed_certs = false
  use_publisher_dns       = true
}

# Output the application details
output "app_name" {
  description = "Name of the created private application"
  value       = netskope_npa_private_app.internal_wiki.private_app_name
}

output "app_hostname" {
  description = "Auto-generated hostname for browser access"
  value       = netskope_npa_private_app.internal_wiki.private_app_hostname
}

output "publisher_used" {
  description = "Publisher assigned to this application"
  value       = local.publisher.publisher_name
}
